1.Find out the selling cost AVG for packages developed 
in pascal.

Answer:
--------
Select AVG(scost) from software
where development='PASCAL'

2.Display Names,Ages of all programmers

Answer:
Select pname as name
      ,datediff(yy,dob,getdate()) as age_sol1
	  ,year(getdate())-year(dob)  as age_sol2
from programmer


3.Display the Names of those who have done the DAP Course.

Ans:
select pname as name 
from studies
where course='DAP'


4.Display the Names and Date of births of all programmers
Born in January
Ans:
Select  pname as names
      ,dob 
 from programmer
 where month(dob)=1
 
5.Which package sold highest no of copies

Answ:
Select  top 1 *
from software
order by sold desc

6.How many programmers done the PGDCA Course
Answ:
Select  count(*) as no_of_programmers
from studies
where course='pgdca'

7.what is the revenue generated by 
Sales of Packages developed in C
Answer:
Select  SUM(scost*sold)total_income_of_c
from software
where development='C'

8.Display the lowest course fee
Answer:

Sol1:

Select  min(coursefee)
from  studies

Sol2:
Select  top 1 course,coursefee
from  studies
order by coursefee asc


9.Display the details of the software developed by Ramesh

Select *
 from software
 where pname='ramesh'
 
10.How many Programmers Studied at sabari.

Select count(*) count_of_programmers
 from studies
 where institute='sabhari'